# Generated by Django 2.0.6 on 2018-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='extraction model name', max_length=200, unique=True)),
            ],
            options={
                'db_table': 'ExtractionModel',
            },
        ),
    ]
