# Generated by Django 2.0.6 on 2018-07-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20180714_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionmodel',
            name='name',
            field=models.CharField(help_text='extraction model name', max_length=200, unique=True),
        ),
    ]
